runtime: python39  # or your desired Python version

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '12345678'
  MYSQL_DB: 'collage6'

# Cloud SQL connection settings
beta_settings:
  cloud_sql_instances: "nomadic-autumn-447716-j4:asia-south1:myproject"  # Your Cloud SQL instance ID


